# https://docs.github.com/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run lint
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test
      - if: env.CC_TEST_REPORTER_ID
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          path: dist/
          name: chartjs-plugin-selectdata-latest
          if-no-files-found: error
  release:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/download-artifact@v2
        with:
          path: dist/
          name: chartjs-plugin-selectdata-latest
      - run: npm ci
      - run: npm run bower
      - run: npm run package
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/*.js
            dist/**/*.min.js
            dist/**/*.tgz
            dist/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          path: dist/
          name: chartjs-plugin-selectdata-latest
          if-no-files-found: error
  publish-to-npm:
    needs: [build-and-test,release]
    if: github.repository_owner == 'interisk-software' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - uses: actions/download-artifact@v2
        with:
          name: chartjs-plugin-selectdata-latest
          path: dist/
      - run: npm ci
      - run: node scripts/publish-to-npm.js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
